### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by marcjansen**
This fixes some typos throughout the codebase. I am unsure why the checks fail, but this might be unrelated.

It might be best to squash all the single commits into one, if you'd prefer this, just tell me so.

Please review.

### CODE REVIEW

**Comment by groldan** [comment]
keep'em coming, it looks like I've to quit drinking

**Comment by marcjansen** [comment]
> keep'em coming, it looks like I've to quit drinking

:joy: ha! No worries, this looks really interesting this is my way of approaching this project. Thanks so much for this!

**Comment by groldan** [comment]
Hi @marcjansen, the build is failing due to some ill-formatted files: 
```
 Failed to execute goal com.coveo:fmt-maven-plugin:2.4.0:check (default) on project gs-cloud-pluggable-catalog-support: Found 2 non-complying files, failing build 
```

This happens if you commit something that has not been formatted previously by the `fmt-maven-plugin`, to enforce everyone to both build before pushing to github and keep a consistent formatting.

As much as I'm loving this pr, please do this before I can merge it:

- squash all commits into a single one
- run `mvn clean install -DskipTests` or at least `mvn fmt:format` befor committing

TIA,
Gabe

**Comment by marcjansen** [comment]
Will do.

**Comment by marcjansen** [comment]
@groldan updated as suggested.

**Comment by groldan** [comment]
Merging, thanks a loth :P

**Pull request merged**
